import harmonyToIntervals from '../src/harmonyToIntervals';
import { chordParserFactory } from 'chord-symbol';

describe('harmonyToIntervals', () => {
	test('is a function', () => {
		expect(typeof harmonyToIntervals).toBe('function');
	});

	const omit3 = { value: '3', type: 'subtract' };
	const omitb3 = { value: '3', alter: '-1', type: 'subtract' };
	const omit5 = { value: '5', type: 'subtract' };

	const add3 = { value: '3', type: 'add' };
	const add4 = { value: '4', type: 'add' };
	const add6 = { value: '6', type: 'add' };
	const addma7 = { value: '7', type: 'add' };
	const addb9 = { value: '9', alter: '-1', type: 'add' };
	const add9 = { value: '9', type: 'add' };
	const addx9 = { value: '9', alter: '1', type: 'add' };
	const add11 = { value: '11', type: 'add' };
	const addx11 = { value: '11', alter: '1', type: 'add' };
	const addb13 = { value: '13', alter: '-1', type: 'add' };
	const add13 = { value: '13', type: 'add' };

	const alterb5 = { value: '5', alter: '-1', type: 'alter' };
	const alterx5 = { value: '5', alter: '1', type: 'alter' };
	const alterb9 = { value: '9', alter: '-1', type: 'alter' };
	const alterx9 = { value: '9', alter: '1', type: 'alter' };
	const alterx11 = { value: '11', alter: '1', type: 'alter' };
	const alterb13 = { value: '13', alter: '-1', type: 'alter' };

	describe.each([
		['C', 'major'],
		['Cm', 'minor'],
		['C+', 'augmented'],
		['C°', 'diminished'],
		['C7', 'dominant'],
		['CM7', 'major-seventh'],
		['Cm7', 'minor-seventh'],
		['C°7', 'diminished-seventh'],
		['C+7', 'augmented-seventh'],
		['Ch', 'half-diminished'],
		['CmM7', 'major-minor'],
		['C6', 'major-sixth'],
		['Cm6', 'minor-sixth'],
		['C9', 'dominant-ninth'],
		['CM9', 'major-ninth'],
		['Cm9', 'minor-ninth'],
		['C11', 'dominant-11th'],
		['CM11', 'major-11th'],
		['Cm11', 'minor-11th'],
		['C13', 'dominant-13th'],
		['CM13', 'major-13th'],
		['Cm13', 'minor-13th'],
		['Csus2', 'suspended-second'],
		['Csus4', 'suspended-fourth'],
		/*
		['C', 'Neapolitan'],
		['C', 'Italian'],
		['C', 'French'],
		['C', 'German'],
		*/
		['C(bass)', 'pedal'],
		['C5', 'power'],
		/*
		['C', 'Tristan'],
		['C', 'other'],
		['C', 'none]'
		 */
		['C(add9)', 'major', [add9]],
		['C(add9,#11)', 'major', [add9, addx11]],
		['Cdim7(add ma7)', 'diminished-seventh', [addma7]],
		['C7(b9,#9,#11)', 'dominant', [alterb9, alterx9, alterx11]],

		// Chords symbols from: Contemporary Music Theory

		['C5', 'power', []],
		['C(omit3)', 'major', [omit3]],
		['Csus', 'suspended-fourth', []],
		['C(b5)', 'major', [alterb5]],
		['C', 'major', []],
		['C+', 'augmented', []],
		['C6(b5)', 'major-sixth', [alterb5]],
		['C6', 'major-sixth', []],
		['C6(#5)', 'major-sixth', [alterx5]],
		['C69', 'major-sixth', [add9]],
		['C69', 'major', [add6, add9]],
		['Cma6', 'major-sixth', []],
		['Cma69', 'major-sixth', [add9]],
		['Cma6(#5)', 'major-sixth', [alterx5]],
		['C69(#11)', 'major-sixth', [add9, alterx11]],
		['Cma7', 'major-seventh', []],
		['Cma7(#5)', 'major-seventh', [alterx5]],
		['Cadd9(omit3)', 'suspended-second', [add9, omit3]],
		['Cma6(b5)', 'major-sixth', [alterb5]],
		['Cadd9', 'major', [add9]],
		['C(add9)', 'major', [add9]],
		['Cma9', 'major-ninth', []],
		['Cma7(b5)', 'major-seventh', [alterb5]],
		['Cma9(no3)', 'major-ninth', [omit3]],
		['Cma9(#11)', 'major-ninth', [alterx11]],
		['Cma9(omit3)', 'major-ninth', [omit3]],
		['Cadd9(no3)', 'major', [add9, omit3]],
		['C°', 'diminished', []],
		['Cmi', 'minor', []],
		['Cmi add9', 'minor', [add9]],
		['Cma13(#11)', 'major-13th', [alterx11]],
		['Cmi6', 'minor-sixth', []],
		['Cmi(add9)', 'minor', [add9]],
		['Cmi69(add11)', 'minor-sixth', [add9, add11]],
		['Cmi(#5)', 'minor', [alterx5]],
		['Cmi7', 'minor-seventh', []],
		['Cmi7(b5)', 'minor-seventh', [alterb5]],
		['Cma13', 'major-13th', []],
		['Cmi7(b5,#5)', 'minor-seventh', [alterb5, alterx5]],
		['Cmi7(b5,add11)', 'minor-seventh', [alterb5, add11]],
		['Cmi7(add11)', 'minor-seventh', [add11]],
		['Cmi9', 'minor-ninth', []],
		['Cmi7(#5)', 'minor-seventh', [alterx5]],
		['Cmi11', 'minor-11th', []],
		['Cmi9(b5)', 'minor-ninth', [alterb5]],
		['Cmi11(b5)', 'minor-11th', [alterb5]],
		['Cmi69', 'minor-sixth', [add9]],
		['Cmi11(b5,b13)', 'minor-11th', [alterb5, alterb13]],
		['Cmi11(b5,no3)', 'minor-11th', [alterb5, omitb3]],
		['Cmi11(b5,#5)', 'minor-11th', [alterb5, alterx5]],
		['Cmi13', 'minor-13th', []],
		['CmiMa9', 'major-minor', [add9]],
		['CmiMa9(add13)', 'major-minor', [add9, add13]], // missing kind: 'major-minor-ninth'
		['CmiMa11', 'major-minor', [add9, add11]], // missing kind: 'major-minor-11th'
		['CmiMa13', 'major-minor', [add9, add11, add13]], // missing kind: 'major-minor-13th'
		['C7', 'dominant', []],
		['CmiMa7', 'major-minor', []],
		['C7sus(b9)', 'dominant', [omit3, add4, alterb9]],
		['C7(b5)', 'dominant', [alterb5]],
		['C7(b5,#9)', 'dominant', [alterb5, alterx9]],
		['C7(b5,#5,b9)', 'dominant', [alterb5, alterx5, alterb9]],
		['C7(b5,#5,#9)', 'dominant', [alterb5, alterx5, alterx9]],
		['C7(b5,#5,b9,#9)', 'dominant', [alterb5, alterx5, alterb9, alterx9]],
		[
			'C7(b5,#5,b9,#9,b13)',
			'dominant',
			[alterb5, alterx5, alterb9, alterx9, alterb13],
		],
		['C7(b5,b9,b13)', 'dominant', [alterb5, alterb9, alterb13]],
		['C7(b5,b9,#9)', 'dominant', [alterb5, alterb9, alterx9]],
		['C7(b5,#5)', 'dominant', [alterb5, alterx5]],
		['C7sus', 'dominant', [omit3, add4]],
		['C7(b5,b9)', 'dominant', [alterb5, alterb9]],
		['C7(b5,#9,b13)', 'dominant', [alterb5, alterx9, alterb13]],
		['C7(b5,b13)', 'dominant', [alterb5, alterb13]],
		['C7(#5)', 'dominant', [alterx5]],
		['C7(#5,b9)', 'dominant', [alterx5, alterb9]],
		['C7(#5,#9)', 'dominant', [alterx5, alterx9]],
		['C7(#5,b9,#9)', 'dominant', [alterx5, alterb9, alterx9]],
		['C7(#5,b9,#11)', 'dominant', [alterx5, alterb9, alterx11]],
		['C7(#5,#9,#11)', 'dominant', [alterx5, alterx9, alterx11]],
		['C7(#5,b9,#9,#11)', 'dominant', [alterx5, alterb9, alterx9, alterx11]],
		['C7(#5, #11)', 'dominant', [alterx5, alterx11]],
		['C7(b9)', 'dominant', [alterb9]],
		['C7(b9,#9)', 'dominant', [alterb9, alterx9]],
		['C7(b9,#11)', 'dominant', [alterb9, alterx11]],
		['C7(b9,#9,#11)', 'dominant', [alterb9, alterx9, alterx11]],
		['C7(b9,#9,b13)', 'dominant', [alterb9, alterx9, alterb13]],
		[
			'C7(b9,#9,#11,b13)',
			'dominant',
			[alterb9, alterx9, alterx11, alterb13],
		],
		['C7(b9,#11,b13)', 'dominant', [alterb9, alterx11, alterb13]],
		['C7(b9,b13)', 'dominant', [alterb9, alterb13]],
		['C7(#9)', 'dominant', [alterx9]],
		['C7(#9,#11)', 'dominant', [alterx9, alterx11]],
		['C7(#9,b13)', 'dominant', [alterx9, alterb13]],
		['C7(#9,#11,b13)', 'dominant', [alterx9, alterx11, alterb13]],
		['C7(#11)', 'dominant', [alterx11]],
		['C7(#11,b13)', 'dominant', [alterx11, alterb13]],
		['C7(b13)', 'dominant', [alterb13]],
		['C9', 'dominant-ninth', []],
		['C9(13)', 'dominant-ninth', [add13]],
		['C9(add13)', 'dominant-ninth', [add13]],
		['C9sus', 'dominant-ninth', [omit3, add4]],
		['C9(b5)', 'dominant-ninth', [alterb5]],
		['C9(b5,#5)', 'dominant-ninth', [alterb5, alterx5]],
		['C9(b5,b13)', 'dominant-ninth', [alterb5, alterb13]],
		['C9(#5,#11)', 'dominant-ninth', [alterx5, alterx11]],
		['C9(#11)', 'dominant-ninth', [alterx11]],
		['C9(#11,b13)', 'dominant-ninth', [alterx11, alterb13]],
		['C11', 'dominant-11th', []],
		['C11(b9)', 'dominant-11th', [alterb9]],
		['C13', 'dominant-13th', []],
		['C13sus', 'dominant-13th', [omit3, add4]],
		['C13(b5)', 'dominant-13th', [alterb5]],
		['C13(b5,b9)', 'dominant-13th', [alterb5, alterb9]],
		['C13(b5,#9)', 'dominant-13th', [alterb5, alterx9]],
		['C13(b5,b9,#9)', 'dominant-13th', [alterb5, alterb9, alterx9]],
		['C13(b9)', 'dominant-13th', [alterb9]],
		['C13(b9,#9)', 'dominant-13th', [alterb9, alterx9]],
		['C13(b9,#11)', 'dominant-13th', [alterb9, alterx11]],
		['C13(b9,#9,#11)', 'dominant-13th', [alterb9, alterx9, alterx11]],
		['C13(#9)', 'dominant-13th', [alterx9]],
		['C13(#9,#11)', 'dominant-13th', [alterx9, alterx11]],
		['C13(#11)', 'dominant-13th', [alterx11]],
		['Cdim', 'diminished', []],
		['Cdim7', 'diminished-seventh', []],
		['Cdim7(add ma7)', 'diminished-seventh', [addma7]],
		['Cdim7(add ma7,9)', 'diminished-seventh', [addma7, add9]],
		['Cdim7(add ma7,9,11)', 'diminished-seventh', [addma7, add9, add11]],
		[
			'Cdim7(add ma7,9,11,b13)',
			'diminished-seventh',
			[addma7, add9, add11, addb13],
		],
		['Cdim7(add ma7,11)', 'diminished-seventh', [addma7, add11]],
		[
			'Cdim7(add ma7,11,b13)',
			'diminished-seventh',
			[addma7, add11, addb13],
		],
		['Cdim7(add ma7,9,b13)', 'diminished-seventh', [addma7, add9, addb13]],
		['Cdim7(add ma7,b13)', 'diminished-seventh', [addma7, addb13]],
		['Cdim7(add 9)', 'diminished-seventh', [add9]],
		['Cdim7(add 9,11)', 'diminished-seventh', [add9, add11]],
		['Cdim7(add 9,11,b13)', 'diminished-seventh', [add9, add11, addb13]],
		['Cdim7(add 9,b13)', 'diminished-seventh', [add9, addb13]],
		['Cdim7(add 11)', 'diminished-seventh', [add11]],
		['Cdim7(add 11,b13)', 'diminished-seventh', [add11, addb13]],
		['Cdim7(add b13)', 'diminished-seventh', [addb13]],

		// Chords symbols from: The New Real Book vol1

		['C bass', 'pedal', []],
		['C', 'major', []],
		['CSUS', 'suspended-fourth', []],
		['C+', 'augmented', []],
		['C6', 'major-sixth', []],
		['C6/9', 'major-sixth', [add9]],
		['CMA7(b5)', 'major-seventh', [alterb5]],
		['C#MA7SUS(b5)', 'major-seventh', [omit3, add4, alterb5]],
		['CMA7', 'major-seventh', []],
		['CMA7(#5)', 'major-seventh', [alterx5]],
		['CMA7(#11)', 'major-seventh', [alterx11]],
		['C(add 9,omit 3)', 'suspended-second', [omit3, add9]],
		['C(add 9)', 'major', [add9]],
		['CMA9', 'major-ninth', []],
		['CMA9(#11)', 'major-ninth', [alterx11]],
		['CMA7(add 13)', 'major-seventh', [add13]],
		['CMA13', 'major-13th', []],
		['CMA13(#11)', 'major-13th', [addx11]],
		['Bb(add 9,add b13)', 'major', [add9, addb13]],
		['A+(add b9,add #9)', 'augmented', [addb9, addx9]],
		['CMI7', 'minor-seventh', []],
		['CMI7(omit 5)', 'minor-seventh', [omit5]],
		['CMI9', 'minor-ninth', []],
		['CMI11', 'minor-11th', []],
		['CMI7(add 11)', 'minor-seventh', [add11]],
		['CMI13', 'minor-13th', []],
		['CMI7(add 13)', 'minor-seventh', [add13]],
		['G#MI7(add 11, omit 5)', 'minor-seventh', [add11, omit5]],
		['Cdim.', 'diminished', []],
		['CMI7(b5)', 'minor-seventh', [alterb5]],
		['CMI9(b5)', 'minor-ninth', [alterb5]],
		['CMI11(b5)', 'minor-11th', [alterb5]],
		['CMI', 'minor', []],
		['CMI6', 'minor-sixth', []],
		['CMI(MA7)', 'major-minor', []],
		['CMI(add9)', 'minor', [add9]],
		['CMI6/9', 'minor-sixth', [add9]],
		['C7', 'dominant', []],
		['C7(omit 3)', 'dominant', [omit3]],
		['C9', 'dominant-ninth', []],
		['C13', 'dominant-13th', []],
		['C7SUS', 'dominant', [omit3, add4]],
		['F#7SUS(add 3)', 'dominant', [omit3, add3, add4]],
		['C9SUS', 'dominant-ninth', [omit3, add4]],
		['C13SUS', 'dominant-13th', [omit3, add4]],
		['C7(b5)', 'dominant', [alterb5]],
		['C7(b5,b9)', 'dominant', [alterb5, alterb9]],
		['C9(b5)', 'dominant-ninth', [alterb5]],
		['C13(b5)', 'dominant-13th', [alterb5]],
		['C7(#11)', 'dominant', [alterx11]],
		['C9(#11)', 'dominant-ninth', [alterx11]],
		['C13(#11)', 'dominant-13th', [alterx11]],
		['C7(b9)', 'dominant', [alterb9]],
		['C7(#9)', 'dominant', [alterx9]],
		['C7(b9,#11)', 'dominant', [alterb9, alterx11]],
		['C7(#9,#11)', 'dominant', [alterx9, alterx11]],
		['C7SUS(b9)', 'dominant', [omit3, add4, alterb9]],
		['C13SUS(b9)', 'dominant-13th', [omit3, add4, alterb9]],
		['C13(b9)', 'dominant-13th', [alterb9]],
		['C13(#11)', 'dominant-13th', [alterx11]],
		['C7(#5)', 'dominant', [alterx5]],
		['C7(#5,b9)', 'dominant', [alterx5, alterb9]],
		['C7(#5,#9)', 'dominant', [alterx5, alterx9]],
		['C9(#5)', 'dominant-ninth', [alterx5]],
		['C°7', 'diminished-seventh', []],
		['C°7(add MA7)', 'diminished-seventh', [addma7]],
		['C/E', 'major', []],
		['C/G', 'major', []],
		['E/C', 'major', []],
		['Bb/C', 'major', []],
		['C(add 9)/E', 'major', [add9]],
		['F/F#', 'major', []],
		['E+/G', 'augmented', []],
		['G7SUS/A', 'dominant', [omit3, add4]],
		['GMA7(#5)/F#', 'major-seventh', [alterx5]],
		['EbMA7(#5)/F', 'major-seventh', [alterx5]],
		['BMA7SUS/F#', 'major-seventh', [omit3, add4]],
	])('%s - %s', (symbol, kind, allDegrees) => {
		test(
			'should yield the same intervals as chord symbol having parsed ' +
				symbol,
			() => {
				const parseChord = chordParserFactory();
				const parsed = parseChord(symbol);
				const intervals = harmonyToIntervals(kind, allDegrees);

				expect(intervals).toEqual(parsed.normalized.intervals);
			}
		);
	});
});
